// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: altimeter.proto

#ifndef PROTOBUF_altimeter_2eproto__INCLUDED
#define PROTOBUF_altimeter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>


#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "time.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_altimeter_2eproto();
void protobuf_AssignDesc_altimeter_2eproto();
void protobuf_ShutdownFile_altimeter_2eproto();

class Altimeter;

// ===================================================================

class GZ_MSGS_VISIBLE Altimeter : public ::google::protobuf::Message {
 public:
  Altimeter();
  virtual ~Altimeter();

  Altimeter(const Altimeter& from);

  inline Altimeter& operator=(const Altimeter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Altimeter& default_instance();

  void Swap(Altimeter* other);

  // implements Message ----------------------------------------------

  Altimeter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Altimeter& from);
  void MergeFrom(const Altimeter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .gazebo.msgs.Time time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline const ::gazebo::msgs::Time& time() const;
  inline ::gazebo::msgs::Time* mutable_time();
  inline ::gazebo::msgs::Time* release_time();
  inline void set_allocated_time(::gazebo::msgs::Time* time);

  // required double vertical_position = 2;
  inline bool has_vertical_position() const;
  inline void clear_vertical_position();
  static const int kVerticalPositionFieldNumber = 2;
  inline double vertical_position() const;
  inline void set_vertical_position(double value);

  // required double vertical_velocity = 3;
  inline bool has_vertical_velocity() const;
  inline void clear_vertical_velocity();
  static const int kVerticalVelocityFieldNumber = 3;
  inline double vertical_velocity() const;
  inline void set_vertical_velocity(double value);

  // required double vertical_reference = 4;
  inline bool has_vertical_reference() const;
  inline void clear_vertical_reference();
  static const int kVerticalReferenceFieldNumber = 4;
  inline double vertical_reference() const;
  inline void set_vertical_reference(double value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Altimeter)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_vertical_position();
  inline void clear_has_vertical_position();
  inline void set_has_vertical_velocity();
  inline void clear_has_vertical_velocity();
  inline void set_has_vertical_reference();
  inline void clear_has_vertical_reference();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::gazebo::msgs::Time* time_;
  double vertical_position_;
  double vertical_velocity_;
  double vertical_reference_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_altimeter_2eproto();
  friend void protobuf_AssignDesc_altimeter_2eproto();
  friend void protobuf_ShutdownFile_altimeter_2eproto();

  void InitAsDefaultInstance();
  static Altimeter* default_instance_;
};
// ===================================================================


// ===================================================================

// Altimeter

// required .gazebo.msgs.Time time = 1;
inline bool Altimeter::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Altimeter::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Altimeter::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Altimeter::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
inline const ::gazebo::msgs::Time& Altimeter::time() const {
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::gazebo::msgs::Time* Altimeter::mutable_time() {
  set_has_time();
  if (time_ == NULL) time_ = new ::gazebo::msgs::Time;
  return time_;
}
inline ::gazebo::msgs::Time* Altimeter::release_time() {
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void Altimeter::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
}

// required double vertical_position = 2;
inline bool Altimeter::has_vertical_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Altimeter::set_has_vertical_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Altimeter::clear_has_vertical_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Altimeter::clear_vertical_position() {
  vertical_position_ = 0;
  clear_has_vertical_position();
}
inline double Altimeter::vertical_position() const {
  return vertical_position_;
}
inline void Altimeter::set_vertical_position(double value) {
  set_has_vertical_position();
  vertical_position_ = value;
}

// required double vertical_velocity = 3;
inline bool Altimeter::has_vertical_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Altimeter::set_has_vertical_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Altimeter::clear_has_vertical_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Altimeter::clear_vertical_velocity() {
  vertical_velocity_ = 0;
  clear_has_vertical_velocity();
}
inline double Altimeter::vertical_velocity() const {
  return vertical_velocity_;
}
inline void Altimeter::set_vertical_velocity(double value) {
  set_has_vertical_velocity();
  vertical_velocity_ = value;
}

// required double vertical_reference = 4;
inline bool Altimeter::has_vertical_reference() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Altimeter::set_has_vertical_reference() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Altimeter::clear_has_vertical_reference() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Altimeter::clear_vertical_reference() {
  vertical_reference_ = 0;
  clear_has_vertical_reference();
}
inline double Altimeter::vertical_reference() const {
  return vertical_reference_;
}
inline void Altimeter::set_vertical_reference(double value) {
  set_has_vertical_reference();
  vertical_reference_ = value;
}


typedef boost::shared_ptr<gazebo::msgs::Altimeter> AltimeterPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::Altimeter const> ConstAltimeterPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_altimeter_2eproto__INCLUDED
