// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_cmd.proto

#ifndef PROTOBUF_camera_5fcmd_2eproto__INCLUDED
#define PROTOBUF_camera_5fcmd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_camera_5fcmd_2eproto();
void protobuf_AssignDesc_camera_5fcmd_2eproto();
void protobuf_ShutdownFile_camera_5fcmd_2eproto();

class CameraCmd;

// ===================================================================

class GZ_MSGS_VISIBLE CameraCmd : public ::google::protobuf::Message {
 public:
  CameraCmd();
  virtual ~CameraCmd();

  CameraCmd(const CameraCmd& from);

  inline CameraCmd& operator=(const CameraCmd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraCmd& default_instance();

  void Swap(CameraCmd* other);

  // implements Message ----------------------------------------------

  CameraCmd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CameraCmd& from);
  void MergeFrom(const CameraCmd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string follow_model = 1;
  inline bool has_follow_model() const;
  inline void clear_follow_model();
  static const int kFollowModelFieldNumber = 1;
  inline const ::std::string& follow_model() const;
  inline void set_follow_model(const ::std::string& value);
  inline void set_follow_model(const char* value);
  inline void set_follow_model(const char* value, size_t size);
  inline ::std::string* mutable_follow_model();
  inline ::std::string* release_follow_model();
  inline void set_allocated_follow_model(::std::string* follow_model);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.CameraCmd)
 private:
  inline void set_has_follow_model();
  inline void clear_has_follow_model();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* follow_model_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_camera_5fcmd_2eproto();
  friend void protobuf_AssignDesc_camera_5fcmd_2eproto();
  friend void protobuf_ShutdownFile_camera_5fcmd_2eproto();

  void InitAsDefaultInstance();
  static CameraCmd* default_instance_;
};
// ===================================================================


// ===================================================================

// CameraCmd

// optional string follow_model = 1;
inline bool CameraCmd::has_follow_model() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CameraCmd::set_has_follow_model() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CameraCmd::clear_has_follow_model() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CameraCmd::clear_follow_model() {
  if (follow_model_ != &::google::protobuf::internal::kEmptyString) {
    follow_model_->clear();
  }
  clear_has_follow_model();
}
inline const ::std::string& CameraCmd::follow_model() const {
  return *follow_model_;
}
inline void CameraCmd::set_follow_model(const ::std::string& value) {
  set_has_follow_model();
  if (follow_model_ == &::google::protobuf::internal::kEmptyString) {
    follow_model_ = new ::std::string;
  }
  follow_model_->assign(value);
}
inline void CameraCmd::set_follow_model(const char* value) {
  set_has_follow_model();
  if (follow_model_ == &::google::protobuf::internal::kEmptyString) {
    follow_model_ = new ::std::string;
  }
  follow_model_->assign(value);
}
inline void CameraCmd::set_follow_model(const char* value, size_t size) {
  set_has_follow_model();
  if (follow_model_ == &::google::protobuf::internal::kEmptyString) {
    follow_model_ = new ::std::string;
  }
  follow_model_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CameraCmd::mutable_follow_model() {
  set_has_follow_model();
  if (follow_model_ == &::google::protobuf::internal::kEmptyString) {
    follow_model_ = new ::std::string;
  }
  return follow_model_;
}
inline ::std::string* CameraCmd::release_follow_model() {
  clear_has_follow_model();
  if (follow_model_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = follow_model_;
    follow_model_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CameraCmd::set_allocated_follow_model(::std::string* follow_model) {
  if (follow_model_ != &::google::protobuf::internal::kEmptyString) {
    delete follow_model_;
  }
  if (follow_model) {
    set_has_follow_model();
    follow_model_ = follow_model;
  } else {
    clear_has_follow_model();
    follow_model_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


typedef boost::shared_ptr<gazebo::msgs::CameraCmd> CameraCmdPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::CameraCmd const> ConstCameraCmdPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_camera_5fcmd_2eproto__INCLUDED
