// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cylindergeom.proto

#ifndef PROTOBUF_cylindergeom_2eproto__INCLUDED
#define PROTOBUF_cylindergeom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_cylindergeom_2eproto();
void protobuf_AssignDesc_cylindergeom_2eproto();
void protobuf_ShutdownFile_cylindergeom_2eproto();

class CylinderGeom;

// ===================================================================

class GZ_MSGS_VISIBLE CylinderGeom : public ::google::protobuf::Message {
 public:
  CylinderGeom();
  virtual ~CylinderGeom();

  CylinderGeom(const CylinderGeom& from);

  inline CylinderGeom& operator=(const CylinderGeom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CylinderGeom& default_instance();

  void Swap(CylinderGeom* other);

  // implements Message ----------------------------------------------

  CylinderGeom* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CylinderGeom& from);
  void MergeFrom(const CylinderGeom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double radius = 1;
  inline bool has_radius() const;
  inline void clear_radius();
  static const int kRadiusFieldNumber = 1;
  inline double radius() const;
  inline void set_radius(double value);

  // required double length = 2;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 2;
  inline double length() const;
  inline void set_length(double value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.CylinderGeom)
 private:
  inline void set_has_radius();
  inline void clear_has_radius();
  inline void set_has_length();
  inline void clear_has_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double radius_;
  double length_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_cylindergeom_2eproto();
  friend void protobuf_AssignDesc_cylindergeom_2eproto();
  friend void protobuf_ShutdownFile_cylindergeom_2eproto();

  void InitAsDefaultInstance();
  static CylinderGeom* default_instance_;
};
// ===================================================================


// ===================================================================

// CylinderGeom

// required double radius = 1;
inline bool CylinderGeom::has_radius() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CylinderGeom::set_has_radius() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CylinderGeom::clear_has_radius() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CylinderGeom::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline double CylinderGeom::radius() const {
  return radius_;
}
inline void CylinderGeom::set_radius(double value) {
  set_has_radius();
  radius_ = value;
}

// required double length = 2;
inline bool CylinderGeom::has_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CylinderGeom::set_has_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CylinderGeom::clear_has_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CylinderGeom::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline double CylinderGeom::length() const {
  return length_;
}
inline void CylinderGeom::set_length(double value) {
  set_has_length();
  length_ = value;
}


typedef boost::shared_ptr<gazebo::msgs::CylinderGeom> CylinderGeomPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::CylinderGeom const> ConstCylinderGeomPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cylindergeom_2eproto__INCLUDED
