// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geometry.proto

#ifndef PROTOBUF_geometry_2eproto__INCLUDED
#define PROTOBUF_geometry_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "boxgeom.pb.h"
#include "cylindergeom.pb.h"
#include "spheregeom.pb.h"
#include "planegeom.pb.h"
#include "imagegeom.pb.h"
#include "heightmapgeom.pb.h"
#include "meshgeom.pb.h"
#include "vector3d.pb.h"
#include "polylinegeom.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_geometry_2eproto();
void protobuf_AssignDesc_geometry_2eproto();
void protobuf_ShutdownFile_geometry_2eproto();

class Geometry;

enum Geometry_Type {
  Geometry_Type_BOX = 1,
  Geometry_Type_CYLINDER = 2,
  Geometry_Type_SPHERE = 3,
  Geometry_Type_PLANE = 4,
  Geometry_Type_IMAGE = 5,
  Geometry_Type_HEIGHTMAP = 6,
  Geometry_Type_MESH = 7,
  Geometry_Type_TRIANGLE_FAN = 8,
  Geometry_Type_LINE_STRIP = 9,
  Geometry_Type_POLYLINE = 10,
  Geometry_Type_EMPTY = 11
};
GZ_MSGS_VISIBLE bool Geometry_Type_IsValid(int value);
const Geometry_Type Geometry_Type_Type_MIN = Geometry_Type_BOX;
const Geometry_Type Geometry_Type_Type_MAX = Geometry_Type_EMPTY;
const int Geometry_Type_Type_ARRAYSIZE = Geometry_Type_Type_MAX + 1;

GZ_MSGS_VISIBLE const ::google::protobuf::EnumDescriptor* Geometry_Type_descriptor();
inline const ::std::string& Geometry_Type_Name(Geometry_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Geometry_Type_descriptor(), value);
}
inline bool Geometry_Type_Parse(
    const ::std::string& name, Geometry_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Geometry_Type>(
    Geometry_Type_descriptor(), name, value);
}
// ===================================================================

class GZ_MSGS_VISIBLE Geometry : public ::google::protobuf::Message {
 public:
  Geometry();
  virtual ~Geometry();

  Geometry(const Geometry& from);

  inline Geometry& operator=(const Geometry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Geometry& default_instance();

  void Swap(Geometry* other);

  // implements Message ----------------------------------------------

  Geometry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Geometry& from);
  void MergeFrom(const Geometry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Geometry_Type Type;
  static const Type BOX = Geometry_Type_BOX;
  static const Type CYLINDER = Geometry_Type_CYLINDER;
  static const Type SPHERE = Geometry_Type_SPHERE;
  static const Type PLANE = Geometry_Type_PLANE;
  static const Type IMAGE = Geometry_Type_IMAGE;
  static const Type HEIGHTMAP = Geometry_Type_HEIGHTMAP;
  static const Type MESH = Geometry_Type_MESH;
  static const Type TRIANGLE_FAN = Geometry_Type_TRIANGLE_FAN;
  static const Type LINE_STRIP = Geometry_Type_LINE_STRIP;
  static const Type POLYLINE = Geometry_Type_POLYLINE;
  static const Type EMPTY = Geometry_Type_EMPTY;
  static inline bool Type_IsValid(int value) {
    return Geometry_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Geometry_Type_Type_MIN;
  static const Type Type_MAX =
    Geometry_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Geometry_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Geometry_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Geometry_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Geometry_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .gazebo.msgs.Geometry.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::gazebo::msgs::Geometry_Type type() const;
  inline void set_type(::gazebo::msgs::Geometry_Type value);

  // optional .gazebo.msgs.BoxGeom box = 2;
  inline bool has_box() const;
  inline void clear_box();
  static const int kBoxFieldNumber = 2;
  inline const ::gazebo::msgs::BoxGeom& box() const;
  inline ::gazebo::msgs::BoxGeom* mutable_box();
  inline ::gazebo::msgs::BoxGeom* release_box();
  inline void set_allocated_box(::gazebo::msgs::BoxGeom* box);

  // optional .gazebo.msgs.CylinderGeom cylinder = 3;
  inline bool has_cylinder() const;
  inline void clear_cylinder();
  static const int kCylinderFieldNumber = 3;
  inline const ::gazebo::msgs::CylinderGeom& cylinder() const;
  inline ::gazebo::msgs::CylinderGeom* mutable_cylinder();
  inline ::gazebo::msgs::CylinderGeom* release_cylinder();
  inline void set_allocated_cylinder(::gazebo::msgs::CylinderGeom* cylinder);

  // optional .gazebo.msgs.PlaneGeom plane = 4;
  inline bool has_plane() const;
  inline void clear_plane();
  static const int kPlaneFieldNumber = 4;
  inline const ::gazebo::msgs::PlaneGeom& plane() const;
  inline ::gazebo::msgs::PlaneGeom* mutable_plane();
  inline ::gazebo::msgs::PlaneGeom* release_plane();
  inline void set_allocated_plane(::gazebo::msgs::PlaneGeom* plane);

  // optional .gazebo.msgs.SphereGeom sphere = 5;
  inline bool has_sphere() const;
  inline void clear_sphere();
  static const int kSphereFieldNumber = 5;
  inline const ::gazebo::msgs::SphereGeom& sphere() const;
  inline ::gazebo::msgs::SphereGeom* mutable_sphere();
  inline ::gazebo::msgs::SphereGeom* release_sphere();
  inline void set_allocated_sphere(::gazebo::msgs::SphereGeom* sphere);

  // optional .gazebo.msgs.ImageGeom image = 6;
  inline bool has_image() const;
  inline void clear_image();
  static const int kImageFieldNumber = 6;
  inline const ::gazebo::msgs::ImageGeom& image() const;
  inline ::gazebo::msgs::ImageGeom* mutable_image();
  inline ::gazebo::msgs::ImageGeom* release_image();
  inline void set_allocated_image(::gazebo::msgs::ImageGeom* image);

  // optional .gazebo.msgs.HeightmapGeom heightmap = 7;
  inline bool has_heightmap() const;
  inline void clear_heightmap();
  static const int kHeightmapFieldNumber = 7;
  inline const ::gazebo::msgs::HeightmapGeom& heightmap() const;
  inline ::gazebo::msgs::HeightmapGeom* mutable_heightmap();
  inline ::gazebo::msgs::HeightmapGeom* release_heightmap();
  inline void set_allocated_heightmap(::gazebo::msgs::HeightmapGeom* heightmap);

  // optional .gazebo.msgs.MeshGeom mesh = 8;
  inline bool has_mesh() const;
  inline void clear_mesh();
  static const int kMeshFieldNumber = 8;
  inline const ::gazebo::msgs::MeshGeom& mesh() const;
  inline ::gazebo::msgs::MeshGeom* mutable_mesh();
  inline ::gazebo::msgs::MeshGeom* release_mesh();
  inline void set_allocated_mesh(::gazebo::msgs::MeshGeom* mesh);

  // repeated .gazebo.msgs.Vector3d points = 9;
  inline int points_size() const;
  inline void clear_points();
  static const int kPointsFieldNumber = 9;
  inline const ::gazebo::msgs::Vector3d& points(int index) const;
  inline ::gazebo::msgs::Vector3d* mutable_points(int index);
  inline ::gazebo::msgs::Vector3d* add_points();
  inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >&
      points() const;
  inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >*
      mutable_points();

  // repeated .gazebo.msgs.Polyline polyline = 10;
  inline int polyline_size() const;
  inline void clear_polyline();
  static const int kPolylineFieldNumber = 10;
  inline const ::gazebo::msgs::Polyline& polyline(int index) const;
  inline ::gazebo::msgs::Polyline* mutable_polyline(int index);
  inline ::gazebo::msgs::Polyline* add_polyline();
  inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Polyline >&
      polyline() const;
  inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Polyline >*
      mutable_polyline();

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Geometry)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_box();
  inline void clear_has_box();
  inline void set_has_cylinder();
  inline void clear_has_cylinder();
  inline void set_has_plane();
  inline void clear_has_plane();
  inline void set_has_sphere();
  inline void clear_has_sphere();
  inline void set_has_image();
  inline void clear_has_image();
  inline void set_has_heightmap();
  inline void clear_has_heightmap();
  inline void set_has_mesh();
  inline void clear_has_mesh();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::gazebo::msgs::BoxGeom* box_;
  ::gazebo::msgs::CylinderGeom* cylinder_;
  ::gazebo::msgs::PlaneGeom* plane_;
  ::gazebo::msgs::SphereGeom* sphere_;
  ::gazebo::msgs::ImageGeom* image_;
  ::gazebo::msgs::HeightmapGeom* heightmap_;
  ::gazebo::msgs::MeshGeom* mesh_;
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d > points_;
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Polyline > polyline_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_geometry_2eproto();
  friend void protobuf_AssignDesc_geometry_2eproto();
  friend void protobuf_ShutdownFile_geometry_2eproto();

  void InitAsDefaultInstance();
  static Geometry* default_instance_;
};
// ===================================================================


// ===================================================================

// Geometry

// optional .gazebo.msgs.Geometry.Type type = 1;
inline bool Geometry::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Geometry::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Geometry::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Geometry::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::gazebo::msgs::Geometry_Type Geometry::type() const {
  return static_cast< ::gazebo::msgs::Geometry_Type >(type_);
}
inline void Geometry::set_type(::gazebo::msgs::Geometry_Type value) {
  assert(::gazebo::msgs::Geometry_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .gazebo.msgs.BoxGeom box = 2;
inline bool Geometry::has_box() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Geometry::set_has_box() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Geometry::clear_has_box() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Geometry::clear_box() {
  if (box_ != NULL) box_->::gazebo::msgs::BoxGeom::Clear();
  clear_has_box();
}
inline const ::gazebo::msgs::BoxGeom& Geometry::box() const {
  return box_ != NULL ? *box_ : *default_instance_->box_;
}
inline ::gazebo::msgs::BoxGeom* Geometry::mutable_box() {
  set_has_box();
  if (box_ == NULL) box_ = new ::gazebo::msgs::BoxGeom;
  return box_;
}
inline ::gazebo::msgs::BoxGeom* Geometry::release_box() {
  clear_has_box();
  ::gazebo::msgs::BoxGeom* temp = box_;
  box_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_box(::gazebo::msgs::BoxGeom* box) {
  delete box_;
  box_ = box;
  if (box) {
    set_has_box();
  } else {
    clear_has_box();
  }
}

// optional .gazebo.msgs.CylinderGeom cylinder = 3;
inline bool Geometry::has_cylinder() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Geometry::set_has_cylinder() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Geometry::clear_has_cylinder() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Geometry::clear_cylinder() {
  if (cylinder_ != NULL) cylinder_->::gazebo::msgs::CylinderGeom::Clear();
  clear_has_cylinder();
}
inline const ::gazebo::msgs::CylinderGeom& Geometry::cylinder() const {
  return cylinder_ != NULL ? *cylinder_ : *default_instance_->cylinder_;
}
inline ::gazebo::msgs::CylinderGeom* Geometry::mutable_cylinder() {
  set_has_cylinder();
  if (cylinder_ == NULL) cylinder_ = new ::gazebo::msgs::CylinderGeom;
  return cylinder_;
}
inline ::gazebo::msgs::CylinderGeom* Geometry::release_cylinder() {
  clear_has_cylinder();
  ::gazebo::msgs::CylinderGeom* temp = cylinder_;
  cylinder_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_cylinder(::gazebo::msgs::CylinderGeom* cylinder) {
  delete cylinder_;
  cylinder_ = cylinder;
  if (cylinder) {
    set_has_cylinder();
  } else {
    clear_has_cylinder();
  }
}

// optional .gazebo.msgs.PlaneGeom plane = 4;
inline bool Geometry::has_plane() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Geometry::set_has_plane() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Geometry::clear_has_plane() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Geometry::clear_plane() {
  if (plane_ != NULL) plane_->::gazebo::msgs::PlaneGeom::Clear();
  clear_has_plane();
}
inline const ::gazebo::msgs::PlaneGeom& Geometry::plane() const {
  return plane_ != NULL ? *plane_ : *default_instance_->plane_;
}
inline ::gazebo::msgs::PlaneGeom* Geometry::mutable_plane() {
  set_has_plane();
  if (plane_ == NULL) plane_ = new ::gazebo::msgs::PlaneGeom;
  return plane_;
}
inline ::gazebo::msgs::PlaneGeom* Geometry::release_plane() {
  clear_has_plane();
  ::gazebo::msgs::PlaneGeom* temp = plane_;
  plane_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_plane(::gazebo::msgs::PlaneGeom* plane) {
  delete plane_;
  plane_ = plane;
  if (plane) {
    set_has_plane();
  } else {
    clear_has_plane();
  }
}

// optional .gazebo.msgs.SphereGeom sphere = 5;
inline bool Geometry::has_sphere() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Geometry::set_has_sphere() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Geometry::clear_has_sphere() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Geometry::clear_sphere() {
  if (sphere_ != NULL) sphere_->::gazebo::msgs::SphereGeom::Clear();
  clear_has_sphere();
}
inline const ::gazebo::msgs::SphereGeom& Geometry::sphere() const {
  return sphere_ != NULL ? *sphere_ : *default_instance_->sphere_;
}
inline ::gazebo::msgs::SphereGeom* Geometry::mutable_sphere() {
  set_has_sphere();
  if (sphere_ == NULL) sphere_ = new ::gazebo::msgs::SphereGeom;
  return sphere_;
}
inline ::gazebo::msgs::SphereGeom* Geometry::release_sphere() {
  clear_has_sphere();
  ::gazebo::msgs::SphereGeom* temp = sphere_;
  sphere_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_sphere(::gazebo::msgs::SphereGeom* sphere) {
  delete sphere_;
  sphere_ = sphere;
  if (sphere) {
    set_has_sphere();
  } else {
    clear_has_sphere();
  }
}

// optional .gazebo.msgs.ImageGeom image = 6;
inline bool Geometry::has_image() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Geometry::set_has_image() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Geometry::clear_has_image() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Geometry::clear_image() {
  if (image_ != NULL) image_->::gazebo::msgs::ImageGeom::Clear();
  clear_has_image();
}
inline const ::gazebo::msgs::ImageGeom& Geometry::image() const {
  return image_ != NULL ? *image_ : *default_instance_->image_;
}
inline ::gazebo::msgs::ImageGeom* Geometry::mutable_image() {
  set_has_image();
  if (image_ == NULL) image_ = new ::gazebo::msgs::ImageGeom;
  return image_;
}
inline ::gazebo::msgs::ImageGeom* Geometry::release_image() {
  clear_has_image();
  ::gazebo::msgs::ImageGeom* temp = image_;
  image_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_image(::gazebo::msgs::ImageGeom* image) {
  delete image_;
  image_ = image;
  if (image) {
    set_has_image();
  } else {
    clear_has_image();
  }
}

// optional .gazebo.msgs.HeightmapGeom heightmap = 7;
inline bool Geometry::has_heightmap() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Geometry::set_has_heightmap() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Geometry::clear_has_heightmap() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Geometry::clear_heightmap() {
  if (heightmap_ != NULL) heightmap_->::gazebo::msgs::HeightmapGeom::Clear();
  clear_has_heightmap();
}
inline const ::gazebo::msgs::HeightmapGeom& Geometry::heightmap() const {
  return heightmap_ != NULL ? *heightmap_ : *default_instance_->heightmap_;
}
inline ::gazebo::msgs::HeightmapGeom* Geometry::mutable_heightmap() {
  set_has_heightmap();
  if (heightmap_ == NULL) heightmap_ = new ::gazebo::msgs::HeightmapGeom;
  return heightmap_;
}
inline ::gazebo::msgs::HeightmapGeom* Geometry::release_heightmap() {
  clear_has_heightmap();
  ::gazebo::msgs::HeightmapGeom* temp = heightmap_;
  heightmap_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_heightmap(::gazebo::msgs::HeightmapGeom* heightmap) {
  delete heightmap_;
  heightmap_ = heightmap;
  if (heightmap) {
    set_has_heightmap();
  } else {
    clear_has_heightmap();
  }
}

// optional .gazebo.msgs.MeshGeom mesh = 8;
inline bool Geometry::has_mesh() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Geometry::set_has_mesh() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Geometry::clear_has_mesh() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Geometry::clear_mesh() {
  if (mesh_ != NULL) mesh_->::gazebo::msgs::MeshGeom::Clear();
  clear_has_mesh();
}
inline const ::gazebo::msgs::MeshGeom& Geometry::mesh() const {
  return mesh_ != NULL ? *mesh_ : *default_instance_->mesh_;
}
inline ::gazebo::msgs::MeshGeom* Geometry::mutable_mesh() {
  set_has_mesh();
  if (mesh_ == NULL) mesh_ = new ::gazebo::msgs::MeshGeom;
  return mesh_;
}
inline ::gazebo::msgs::MeshGeom* Geometry::release_mesh() {
  clear_has_mesh();
  ::gazebo::msgs::MeshGeom* temp = mesh_;
  mesh_ = NULL;
  return temp;
}
inline void Geometry::set_allocated_mesh(::gazebo::msgs::MeshGeom* mesh) {
  delete mesh_;
  mesh_ = mesh;
  if (mesh) {
    set_has_mesh();
  } else {
    clear_has_mesh();
  }
}

// repeated .gazebo.msgs.Vector3d points = 9;
inline int Geometry::points_size() const {
  return points_.size();
}
inline void Geometry::clear_points() {
  points_.Clear();
}
inline const ::gazebo::msgs::Vector3d& Geometry::points(int index) const {
  return points_.Get(index);
}
inline ::gazebo::msgs::Vector3d* Geometry::mutable_points(int index) {
  return points_.Mutable(index);
}
inline ::gazebo::msgs::Vector3d* Geometry::add_points() {
  return points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >&
Geometry::points() const {
  return points_;
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Vector3d >*
Geometry::mutable_points() {
  return &points_;
}

// repeated .gazebo.msgs.Polyline polyline = 10;
inline int Geometry::polyline_size() const {
  return polyline_.size();
}
inline void Geometry::clear_polyline() {
  polyline_.Clear();
}
inline const ::gazebo::msgs::Polyline& Geometry::polyline(int index) const {
  return polyline_.Get(index);
}
inline ::gazebo::msgs::Polyline* Geometry::mutable_polyline(int index) {
  return polyline_.Mutable(index);
}
inline ::gazebo::msgs::Polyline* Geometry::add_polyline() {
  return polyline_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Polyline >&
Geometry::polyline() const {
  return polyline_;
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Polyline >*
Geometry::mutable_polyline() {
  return &polyline_;
}


typedef boost::shared_ptr<gazebo::msgs::Geometry> GeometryPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gazebo::msgs::Geometry_Type>() {
  return ::gazebo::msgs::Geometry_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::Geometry const> ConstGeometryPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_geometry_2eproto__INCLUDED
