// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gui_camera.proto

#ifndef PROTOBUF_gui_5fcamera_2eproto__INCLUDED
#define PROTOBUF_gui_5fcamera_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "pose.pb.h"
#include "track_visual.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_gui_5fcamera_2eproto();
void protobuf_AssignDesc_gui_5fcamera_2eproto();
void protobuf_ShutdownFile_gui_5fcamera_2eproto();

class GUICamera;

// ===================================================================

class GZ_MSGS_VISIBLE GUICamera : public ::google::protobuf::Message {
 public:
  GUICamera();
  virtual ~GUICamera();

  GUICamera(const GUICamera& from);

  inline GUICamera& operator=(const GUICamera& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GUICamera& default_instance();

  void Swap(GUICamera* other);

  // implements Message ----------------------------------------------

  GUICamera* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GUICamera& from);
  void MergeFrom(const GUICamera& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string view_controller = 2;
  inline bool has_view_controller() const;
  inline void clear_view_controller();
  static const int kViewControllerFieldNumber = 2;
  inline const ::std::string& view_controller() const;
  inline void set_view_controller(const ::std::string& value);
  inline void set_view_controller(const char* value);
  inline void set_view_controller(const char* value, size_t size);
  inline ::std::string* mutable_view_controller();
  inline ::std::string* release_view_controller();
  inline void set_allocated_view_controller(::std::string* view_controller);

  // optional .gazebo.msgs.Pose pose = 3;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 3;
  inline const ::gazebo::msgs::Pose& pose() const;
  inline ::gazebo::msgs::Pose* mutable_pose();
  inline ::gazebo::msgs::Pose* release_pose();
  inline void set_allocated_pose(::gazebo::msgs::Pose* pose);

  // optional .gazebo.msgs.TrackVisual track = 4;
  inline bool has_track() const;
  inline void clear_track();
  static const int kTrackFieldNumber = 4;
  inline const ::gazebo::msgs::TrackVisual& track() const;
  inline ::gazebo::msgs::TrackVisual* mutable_track();
  inline ::gazebo::msgs::TrackVisual* release_track();
  inline void set_allocated_track(::gazebo::msgs::TrackVisual* track);

  // optional string projection_type = 5;
  inline bool has_projection_type() const;
  inline void clear_projection_type();
  static const int kProjectionTypeFieldNumber = 5;
  inline const ::std::string& projection_type() const;
  inline void set_projection_type(const ::std::string& value);
  inline void set_projection_type(const char* value);
  inline void set_projection_type(const char* value, size_t size);
  inline ::std::string* mutable_projection_type();
  inline ::std::string* release_projection_type();
  inline void set_allocated_projection_type(::std::string* projection_type);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.GUICamera)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_view_controller();
  inline void clear_has_view_controller();
  inline void set_has_pose();
  inline void clear_has_pose();
  inline void set_has_track();
  inline void clear_has_track();
  inline void set_has_projection_type();
  inline void clear_has_projection_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::std::string* view_controller_;
  ::gazebo::msgs::Pose* pose_;
  ::gazebo::msgs::TrackVisual* track_;
  ::std::string* projection_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_gui_5fcamera_2eproto();
  friend void protobuf_AssignDesc_gui_5fcamera_2eproto();
  friend void protobuf_ShutdownFile_gui_5fcamera_2eproto();

  void InitAsDefaultInstance();
  static GUICamera* default_instance_;
};
// ===================================================================


// ===================================================================

// GUICamera

// required string name = 1;
inline bool GUICamera::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GUICamera::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GUICamera::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GUICamera::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& GUICamera::name() const {
  return *name_;
}
inline void GUICamera::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void GUICamera::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void GUICamera::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GUICamera::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* GUICamera::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GUICamera::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string view_controller = 2;
inline bool GUICamera::has_view_controller() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GUICamera::set_has_view_controller() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GUICamera::clear_has_view_controller() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GUICamera::clear_view_controller() {
  if (view_controller_ != &::google::protobuf::internal::kEmptyString) {
    view_controller_->clear();
  }
  clear_has_view_controller();
}
inline const ::std::string& GUICamera::view_controller() const {
  return *view_controller_;
}
inline void GUICamera::set_view_controller(const ::std::string& value) {
  set_has_view_controller();
  if (view_controller_ == &::google::protobuf::internal::kEmptyString) {
    view_controller_ = new ::std::string;
  }
  view_controller_->assign(value);
}
inline void GUICamera::set_view_controller(const char* value) {
  set_has_view_controller();
  if (view_controller_ == &::google::protobuf::internal::kEmptyString) {
    view_controller_ = new ::std::string;
  }
  view_controller_->assign(value);
}
inline void GUICamera::set_view_controller(const char* value, size_t size) {
  set_has_view_controller();
  if (view_controller_ == &::google::protobuf::internal::kEmptyString) {
    view_controller_ = new ::std::string;
  }
  view_controller_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GUICamera::mutable_view_controller() {
  set_has_view_controller();
  if (view_controller_ == &::google::protobuf::internal::kEmptyString) {
    view_controller_ = new ::std::string;
  }
  return view_controller_;
}
inline ::std::string* GUICamera::release_view_controller() {
  clear_has_view_controller();
  if (view_controller_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = view_controller_;
    view_controller_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GUICamera::set_allocated_view_controller(::std::string* view_controller) {
  if (view_controller_ != &::google::protobuf::internal::kEmptyString) {
    delete view_controller_;
  }
  if (view_controller) {
    set_has_view_controller();
    view_controller_ = view_controller;
  } else {
    clear_has_view_controller();
    view_controller_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .gazebo.msgs.Pose pose = 3;
inline bool GUICamera::has_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GUICamera::set_has_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GUICamera::clear_has_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GUICamera::clear_pose() {
  if (pose_ != NULL) pose_->::gazebo::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::gazebo::msgs::Pose& GUICamera::pose() const {
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::gazebo::msgs::Pose* GUICamera::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::gazebo::msgs::Pose;
  return pose_;
}
inline ::gazebo::msgs::Pose* GUICamera::release_pose() {
  clear_has_pose();
  ::gazebo::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void GUICamera::set_allocated_pose(::gazebo::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
}

// optional .gazebo.msgs.TrackVisual track = 4;
inline bool GUICamera::has_track() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GUICamera::set_has_track() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GUICamera::clear_has_track() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GUICamera::clear_track() {
  if (track_ != NULL) track_->::gazebo::msgs::TrackVisual::Clear();
  clear_has_track();
}
inline const ::gazebo::msgs::TrackVisual& GUICamera::track() const {
  return track_ != NULL ? *track_ : *default_instance_->track_;
}
inline ::gazebo::msgs::TrackVisual* GUICamera::mutable_track() {
  set_has_track();
  if (track_ == NULL) track_ = new ::gazebo::msgs::TrackVisual;
  return track_;
}
inline ::gazebo::msgs::TrackVisual* GUICamera::release_track() {
  clear_has_track();
  ::gazebo::msgs::TrackVisual* temp = track_;
  track_ = NULL;
  return temp;
}
inline void GUICamera::set_allocated_track(::gazebo::msgs::TrackVisual* track) {
  delete track_;
  track_ = track;
  if (track) {
    set_has_track();
  } else {
    clear_has_track();
  }
}

// optional string projection_type = 5;
inline bool GUICamera::has_projection_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GUICamera::set_has_projection_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GUICamera::clear_has_projection_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GUICamera::clear_projection_type() {
  if (projection_type_ != &::google::protobuf::internal::kEmptyString) {
    projection_type_->clear();
  }
  clear_has_projection_type();
}
inline const ::std::string& GUICamera::projection_type() const {
  return *projection_type_;
}
inline void GUICamera::set_projection_type(const ::std::string& value) {
  set_has_projection_type();
  if (projection_type_ == &::google::protobuf::internal::kEmptyString) {
    projection_type_ = new ::std::string;
  }
  projection_type_->assign(value);
}
inline void GUICamera::set_projection_type(const char* value) {
  set_has_projection_type();
  if (projection_type_ == &::google::protobuf::internal::kEmptyString) {
    projection_type_ = new ::std::string;
  }
  projection_type_->assign(value);
}
inline void GUICamera::set_projection_type(const char* value, size_t size) {
  set_has_projection_type();
  if (projection_type_ == &::google::protobuf::internal::kEmptyString) {
    projection_type_ = new ::std::string;
  }
  projection_type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GUICamera::mutable_projection_type() {
  set_has_projection_type();
  if (projection_type_ == &::google::protobuf::internal::kEmptyString) {
    projection_type_ = new ::std::string;
  }
  return projection_type_;
}
inline ::std::string* GUICamera::release_projection_type() {
  clear_has_projection_type();
  if (projection_type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = projection_type_;
    projection_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GUICamera::set_allocated_projection_type(::std::string* projection_type) {
  if (projection_type_ != &::google::protobuf::internal::kEmptyString) {
    delete projection_type_;
  }
  if (projection_type) {
    set_has_projection_type();
    projection_type_ = projection_type;
  } else {
    clear_has_projection_type();
    projection_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


typedef boost::shared_ptr<gazebo::msgs::GUICamera> GUICameraPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::GUICamera const> ConstGUICameraPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gui_5fcamera_2eproto__INCLUDED
