// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imagegeom.proto

#ifndef PROTOBUF_imagegeom_2eproto__INCLUDED
#define PROTOBUF_imagegeom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_imagegeom_2eproto();
void protobuf_AssignDesc_imagegeom_2eproto();
void protobuf_ShutdownFile_imagegeom_2eproto();

class ImageGeom;

// ===================================================================

class GZ_MSGS_VISIBLE ImageGeom : public ::google::protobuf::Message {
 public:
  ImageGeom();
  virtual ~ImageGeom();

  ImageGeom(const ImageGeom& from);

  inline ImageGeom& operator=(const ImageGeom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImageGeom& default_instance();

  void Swap(ImageGeom* other);

  // implements Message ----------------------------------------------

  ImageGeom* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImageGeom& from);
  void MergeFrom(const ImageGeom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string uri = 1;
  inline bool has_uri() const;
  inline void clear_uri();
  static const int kUriFieldNumber = 1;
  inline const ::std::string& uri() const;
  inline void set_uri(const ::std::string& value);
  inline void set_uri(const char* value);
  inline void set_uri(const char* value, size_t size);
  inline ::std::string* mutable_uri();
  inline ::std::string* release_uri();
  inline void set_allocated_uri(::std::string* uri);

  // optional double scale = 2;
  inline bool has_scale() const;
  inline void clear_scale();
  static const int kScaleFieldNumber = 2;
  inline double scale() const;
  inline void set_scale(double value);

  // optional int32 threshold = 3 [default = 255];
  inline bool has_threshold() const;
  inline void clear_threshold();
  static const int kThresholdFieldNumber = 3;
  inline ::google::protobuf::int32 threshold() const;
  inline void set_threshold(::google::protobuf::int32 value);

  // optional double height = 4;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 4;
  inline double height() const;
  inline void set_height(double value);

  // optional int32 granularity = 5;
  inline bool has_granularity() const;
  inline void clear_granularity();
  static const int kGranularityFieldNumber = 5;
  inline ::google::protobuf::int32 granularity() const;
  inline void set_granularity(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.ImageGeom)
 private:
  inline void set_has_uri();
  inline void clear_has_uri();
  inline void set_has_scale();
  inline void clear_has_scale();
  inline void set_has_threshold();
  inline void clear_has_threshold();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_granularity();
  inline void clear_has_granularity();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* uri_;
  double scale_;
  double height_;
  ::google::protobuf::int32 threshold_;
  ::google::protobuf::int32 granularity_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_imagegeom_2eproto();
  friend void protobuf_AssignDesc_imagegeom_2eproto();
  friend void protobuf_ShutdownFile_imagegeom_2eproto();

  void InitAsDefaultInstance();
  static ImageGeom* default_instance_;
};
// ===================================================================


// ===================================================================

// ImageGeom

// required string uri = 1;
inline bool ImageGeom::has_uri() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImageGeom::set_has_uri() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImageGeom::clear_has_uri() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImageGeom::clear_uri() {
  if (uri_ != &::google::protobuf::internal::kEmptyString) {
    uri_->clear();
  }
  clear_has_uri();
}
inline const ::std::string& ImageGeom::uri() const {
  return *uri_;
}
inline void ImageGeom::set_uri(const ::std::string& value) {
  set_has_uri();
  if (uri_ == &::google::protobuf::internal::kEmptyString) {
    uri_ = new ::std::string;
  }
  uri_->assign(value);
}
inline void ImageGeom::set_uri(const char* value) {
  set_has_uri();
  if (uri_ == &::google::protobuf::internal::kEmptyString) {
    uri_ = new ::std::string;
  }
  uri_->assign(value);
}
inline void ImageGeom::set_uri(const char* value, size_t size) {
  set_has_uri();
  if (uri_ == &::google::protobuf::internal::kEmptyString) {
    uri_ = new ::std::string;
  }
  uri_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ImageGeom::mutable_uri() {
  set_has_uri();
  if (uri_ == &::google::protobuf::internal::kEmptyString) {
    uri_ = new ::std::string;
  }
  return uri_;
}
inline ::std::string* ImageGeom::release_uri() {
  clear_has_uri();
  if (uri_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = uri_;
    uri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ImageGeom::set_allocated_uri(::std::string* uri) {
  if (uri_ != &::google::protobuf::internal::kEmptyString) {
    delete uri_;
  }
  if (uri) {
    set_has_uri();
    uri_ = uri;
  } else {
    clear_has_uri();
    uri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional double scale = 2;
inline bool ImageGeom::has_scale() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ImageGeom::set_has_scale() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ImageGeom::clear_has_scale() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ImageGeom::clear_scale() {
  scale_ = 0;
  clear_has_scale();
}
inline double ImageGeom::scale() const {
  return scale_;
}
inline void ImageGeom::set_scale(double value) {
  set_has_scale();
  scale_ = value;
}

// optional int32 threshold = 3 [default = 255];
inline bool ImageGeom::has_threshold() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ImageGeom::set_has_threshold() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ImageGeom::clear_has_threshold() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ImageGeom::clear_threshold() {
  threshold_ = 255;
  clear_has_threshold();
}
inline ::google::protobuf::int32 ImageGeom::threshold() const {
  return threshold_;
}
inline void ImageGeom::set_threshold(::google::protobuf::int32 value) {
  set_has_threshold();
  threshold_ = value;
}

// optional double height = 4;
inline bool ImageGeom::has_height() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ImageGeom::set_has_height() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ImageGeom::clear_has_height() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ImageGeom::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline double ImageGeom::height() const {
  return height_;
}
inline void ImageGeom::set_height(double value) {
  set_has_height();
  height_ = value;
}

// optional int32 granularity = 5;
inline bool ImageGeom::has_granularity() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ImageGeom::set_has_granularity() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ImageGeom::clear_has_granularity() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ImageGeom::clear_granularity() {
  granularity_ = 0;
  clear_has_granularity();
}
inline ::google::protobuf::int32 ImageGeom::granularity() const {
  return granularity_;
}
inline void ImageGeom::set_granularity(::google::protobuf::int32 value) {
  set_has_granularity();
  granularity_ = value;
}


typedef boost::shared_ptr<gazebo::msgs::ImageGeom> ImageGeomPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::ImageGeom const> ConstImageGeomPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_imagegeom_2eproto__INCLUDED
