// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_wrench_stamped.proto

#ifndef PROTOBUF_joint_5fwrench_5fstamped_2eproto__INCLUDED
#define PROTOBUF_joint_5fwrench_5fstamped_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "joint_wrench.pb.h"
#include "time.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_joint_5fwrench_5fstamped_2eproto();
void protobuf_AssignDesc_joint_5fwrench_5fstamped_2eproto();
void protobuf_ShutdownFile_joint_5fwrench_5fstamped_2eproto();

class ForceTorque;

// ===================================================================

class GZ_MSGS_VISIBLE ForceTorque : public ::google::protobuf::Message {
 public:
  ForceTorque();
  virtual ~ForceTorque();

  ForceTorque(const ForceTorque& from);

  inline ForceTorque& operator=(const ForceTorque& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ForceTorque& default_instance();

  void Swap(ForceTorque* other);

  // implements Message ----------------------------------------------

  ForceTorque* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ForceTorque& from);
  void MergeFrom(const ForceTorque& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gazebo.msgs.JointWrench wrench = 1;
  inline int wrench_size() const;
  inline void clear_wrench();
  static const int kWrenchFieldNumber = 1;
  inline const ::gazebo::msgs::JointWrench& wrench(int index) const;
  inline ::gazebo::msgs::JointWrench* mutable_wrench(int index);
  inline ::gazebo::msgs::JointWrench* add_wrench();
  inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::JointWrench >&
      wrench() const;
  inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::JointWrench >*
      mutable_wrench();

  // required .gazebo.msgs.Time time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline const ::gazebo::msgs::Time& time() const;
  inline ::gazebo::msgs::Time* mutable_time();
  inline ::gazebo::msgs::Time* release_time();
  inline void set_allocated_time(::gazebo::msgs::Time* time);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.ForceTorque)
 private:
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::JointWrench > wrench_;
  ::gazebo::msgs::Time* time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_joint_5fwrench_5fstamped_2eproto();
  friend void protobuf_AssignDesc_joint_5fwrench_5fstamped_2eproto();
  friend void protobuf_ShutdownFile_joint_5fwrench_5fstamped_2eproto();

  void InitAsDefaultInstance();
  static ForceTorque* default_instance_;
};
// ===================================================================


// ===================================================================

// ForceTorque

// repeated .gazebo.msgs.JointWrench wrench = 1;
inline int ForceTorque::wrench_size() const {
  return wrench_.size();
}
inline void ForceTorque::clear_wrench() {
  wrench_.Clear();
}
inline const ::gazebo::msgs::JointWrench& ForceTorque::wrench(int index) const {
  return wrench_.Get(index);
}
inline ::gazebo::msgs::JointWrench* ForceTorque::mutable_wrench(int index) {
  return wrench_.Mutable(index);
}
inline ::gazebo::msgs::JointWrench* ForceTorque::add_wrench() {
  return wrench_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::JointWrench >&
ForceTorque::wrench() const {
  return wrench_;
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::JointWrench >*
ForceTorque::mutable_wrench() {
  return &wrench_;
}

// required .gazebo.msgs.Time time = 2;
inline bool ForceTorque::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ForceTorque::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ForceTorque::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ForceTorque::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
inline const ::gazebo::msgs::Time& ForceTorque::time() const {
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::gazebo::msgs::Time* ForceTorque::mutable_time() {
  set_has_time();
  if (time_ == NULL) time_ = new ::gazebo::msgs::Time;
  return time_;
}
inline ::gazebo::msgs::Time* ForceTorque::release_time() {
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void ForceTorque::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
}


typedef boost::shared_ptr<gazebo::msgs::ForceTorque> ForceTorquePtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::ForceTorque const> ConstForceTorquePtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_joint_5fwrench_5fstamped_2eproto__INCLUDED
