// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logical_camera_image.proto

#ifndef PROTOBUF_logical_5fcamera_5fimage_2eproto__INCLUDED
#define PROTOBUF_logical_5fcamera_5fimage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "pose.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_logical_5fcamera_5fimage_2eproto();
void protobuf_AssignDesc_logical_5fcamera_5fimage_2eproto();
void protobuf_ShutdownFile_logical_5fcamera_5fimage_2eproto();

class LogicalCameraImage;
class LogicalCameraImage_Model;

// ===================================================================

class GZ_MSGS_VISIBLE LogicalCameraImage_Model : public ::google::protobuf::Message {
 public:
  LogicalCameraImage_Model();
  virtual ~LogicalCameraImage_Model();

  LogicalCameraImage_Model(const LogicalCameraImage_Model& from);

  inline LogicalCameraImage_Model& operator=(const LogicalCameraImage_Model& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogicalCameraImage_Model& default_instance();

  void Swap(LogicalCameraImage_Model* other);

  // implements Message ----------------------------------------------

  LogicalCameraImage_Model* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogicalCameraImage_Model& from);
  void MergeFrom(const LogicalCameraImage_Model& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .gazebo.msgs.Pose pose = 2;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 2;
  inline const ::gazebo::msgs::Pose& pose() const;
  inline ::gazebo::msgs::Pose* mutable_pose();
  inline ::gazebo::msgs::Pose* release_pose();
  inline void set_allocated_pose(::gazebo::msgs::Pose* pose);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.LogicalCameraImage.Model)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::gazebo::msgs::Pose* pose_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_logical_5fcamera_5fimage_2eproto();
  friend void protobuf_AssignDesc_logical_5fcamera_5fimage_2eproto();
  friend void protobuf_ShutdownFile_logical_5fcamera_5fimage_2eproto();

  void InitAsDefaultInstance();
  static LogicalCameraImage_Model* default_instance_;
};
// -------------------------------------------------------------------

class GZ_MSGS_VISIBLE LogicalCameraImage : public ::google::protobuf::Message {
 public:
  LogicalCameraImage();
  virtual ~LogicalCameraImage();

  LogicalCameraImage(const LogicalCameraImage& from);

  inline LogicalCameraImage& operator=(const LogicalCameraImage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogicalCameraImage& default_instance();

  void Swap(LogicalCameraImage* other);

  // implements Message ----------------------------------------------

  LogicalCameraImage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogicalCameraImage& from);
  void MergeFrom(const LogicalCameraImage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LogicalCameraImage_Model Model;

  // accessors -------------------------------------------------------

  // required .gazebo.msgs.Pose pose = 1;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 1;
  inline const ::gazebo::msgs::Pose& pose() const;
  inline ::gazebo::msgs::Pose* mutable_pose();
  inline ::gazebo::msgs::Pose* release_pose();
  inline void set_allocated_pose(::gazebo::msgs::Pose* pose);

  // repeated .gazebo.msgs.LogicalCameraImage.Model model = 2;
  inline int model_size() const;
  inline void clear_model();
  static const int kModelFieldNumber = 2;
  inline const ::gazebo::msgs::LogicalCameraImage_Model& model(int index) const;
  inline ::gazebo::msgs::LogicalCameraImage_Model* mutable_model(int index);
  inline ::gazebo::msgs::LogicalCameraImage_Model* add_model();
  inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::LogicalCameraImage_Model >&
      model() const;
  inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::LogicalCameraImage_Model >*
      mutable_model();

  // @@protoc_insertion_point(class_scope:gazebo.msgs.LogicalCameraImage)
 private:
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::gazebo::msgs::Pose* pose_;
  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::LogicalCameraImage_Model > model_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_logical_5fcamera_5fimage_2eproto();
  friend void protobuf_AssignDesc_logical_5fcamera_5fimage_2eproto();
  friend void protobuf_ShutdownFile_logical_5fcamera_5fimage_2eproto();

  void InitAsDefaultInstance();
  static LogicalCameraImage* default_instance_;
};
// ===================================================================


// ===================================================================

// LogicalCameraImage_Model

// required string name = 1;
inline bool LogicalCameraImage_Model::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogicalCameraImage_Model::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogicalCameraImage_Model::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogicalCameraImage_Model::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& LogicalCameraImage_Model::name() const {
  return *name_;
}
inline void LogicalCameraImage_Model::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void LogicalCameraImage_Model::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void LogicalCameraImage_Model::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LogicalCameraImage_Model::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* LogicalCameraImage_Model::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LogicalCameraImage_Model::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .gazebo.msgs.Pose pose = 2;
inline bool LogicalCameraImage_Model::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogicalCameraImage_Model::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogicalCameraImage_Model::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogicalCameraImage_Model::clear_pose() {
  if (pose_ != NULL) pose_->::gazebo::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::gazebo::msgs::Pose& LogicalCameraImage_Model::pose() const {
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::gazebo::msgs::Pose* LogicalCameraImage_Model::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::gazebo::msgs::Pose;
  return pose_;
}
inline ::gazebo::msgs::Pose* LogicalCameraImage_Model::release_pose() {
  clear_has_pose();
  ::gazebo::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LogicalCameraImage_Model::set_allocated_pose(::gazebo::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
}

// -------------------------------------------------------------------

// LogicalCameraImage

// required .gazebo.msgs.Pose pose = 1;
inline bool LogicalCameraImage::has_pose() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogicalCameraImage::set_has_pose() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogicalCameraImage::clear_has_pose() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogicalCameraImage::clear_pose() {
  if (pose_ != NULL) pose_->::gazebo::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::gazebo::msgs::Pose& LogicalCameraImage::pose() const {
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::gazebo::msgs::Pose* LogicalCameraImage::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::gazebo::msgs::Pose;
  return pose_;
}
inline ::gazebo::msgs::Pose* LogicalCameraImage::release_pose() {
  clear_has_pose();
  ::gazebo::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LogicalCameraImage::set_allocated_pose(::gazebo::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
}

// repeated .gazebo.msgs.LogicalCameraImage.Model model = 2;
inline int LogicalCameraImage::model_size() const {
  return model_.size();
}
inline void LogicalCameraImage::clear_model() {
  model_.Clear();
}
inline const ::gazebo::msgs::LogicalCameraImage_Model& LogicalCameraImage::model(int index) const {
  return model_.Get(index);
}
inline ::gazebo::msgs::LogicalCameraImage_Model* LogicalCameraImage::mutable_model(int index) {
  return model_.Mutable(index);
}
inline ::gazebo::msgs::LogicalCameraImage_Model* LogicalCameraImage::add_model() {
  return model_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::LogicalCameraImage_Model >&
LogicalCameraImage::model() const {
  return model_;
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::LogicalCameraImage_Model >*
LogicalCameraImage::mutable_model() {
  return &model_;
}


typedef boost::shared_ptr<gazebo::msgs::LogicalCameraImage> LogicalCameraImagePtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::LogicalCameraImage const> ConstLogicalCameraImagePtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_logical_5fcamera_5fimage_2eproto__INCLUDED
