// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: material.proto

#ifndef PROTOBUF_material_2eproto__INCLUDED
#define PROTOBUF_material_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "color.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_material_2eproto();
void protobuf_AssignDesc_material_2eproto();
void protobuf_ShutdownFile_material_2eproto();

class Material;
class Material_Script;

enum Material_ShaderType {
  Material_ShaderType_VERTEX = 1,
  Material_ShaderType_PIXEL = 2,
  Material_ShaderType_NORMAL_MAP_OBJECT_SPACE = 3,
  Material_ShaderType_NORMAL_MAP_TANGENT_SPACE = 4
};
GZ_MSGS_VISIBLE bool Material_ShaderType_IsValid(int value);
const Material_ShaderType Material_ShaderType_ShaderType_MIN = Material_ShaderType_VERTEX;
const Material_ShaderType Material_ShaderType_ShaderType_MAX = Material_ShaderType_NORMAL_MAP_TANGENT_SPACE;
const int Material_ShaderType_ShaderType_ARRAYSIZE = Material_ShaderType_ShaderType_MAX + 1;

GZ_MSGS_VISIBLE const ::google::protobuf::EnumDescriptor* Material_ShaderType_descriptor();
inline const ::std::string& Material_ShaderType_Name(Material_ShaderType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Material_ShaderType_descriptor(), value);
}
inline bool Material_ShaderType_Parse(
    const ::std::string& name, Material_ShaderType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Material_ShaderType>(
    Material_ShaderType_descriptor(), name, value);
}
// ===================================================================

class GZ_MSGS_VISIBLE Material_Script : public ::google::protobuf::Message {
 public:
  Material_Script();
  virtual ~Material_Script();

  Material_Script(const Material_Script& from);

  inline Material_Script& operator=(const Material_Script& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Material_Script& default_instance();

  void Swap(Material_Script* other);

  // implements Message ----------------------------------------------

  Material_Script* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Material_Script& from);
  void MergeFrom(const Material_Script& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string uri = 1;
  inline int uri_size() const;
  inline void clear_uri();
  static const int kUriFieldNumber = 1;
  inline const ::std::string& uri(int index) const;
  inline ::std::string* mutable_uri(int index);
  inline void set_uri(int index, const ::std::string& value);
  inline void set_uri(int index, const char* value);
  inline void set_uri(int index, const char* value, size_t size);
  inline ::std::string* add_uri();
  inline void add_uri(const ::std::string& value);
  inline void add_uri(const char* value);
  inline void add_uri(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& uri() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_uri();

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Material.Script)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> uri_;
  ::std::string* name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_material_2eproto();
  friend void protobuf_AssignDesc_material_2eproto();
  friend void protobuf_ShutdownFile_material_2eproto();

  void InitAsDefaultInstance();
  static Material_Script* default_instance_;
};
// -------------------------------------------------------------------

class GZ_MSGS_VISIBLE Material : public ::google::protobuf::Message {
 public:
  Material();
  virtual ~Material();

  Material(const Material& from);

  inline Material& operator=(const Material& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Material& default_instance();

  void Swap(Material* other);

  // implements Message ----------------------------------------------

  Material* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Material& from);
  void MergeFrom(const Material& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Material_Script Script;

  typedef Material_ShaderType ShaderType;
  static const ShaderType VERTEX = Material_ShaderType_VERTEX;
  static const ShaderType PIXEL = Material_ShaderType_PIXEL;
  static const ShaderType NORMAL_MAP_OBJECT_SPACE = Material_ShaderType_NORMAL_MAP_OBJECT_SPACE;
  static const ShaderType NORMAL_MAP_TANGENT_SPACE = Material_ShaderType_NORMAL_MAP_TANGENT_SPACE;
  static inline bool ShaderType_IsValid(int value) {
    return Material_ShaderType_IsValid(value);
  }
  static const ShaderType ShaderType_MIN =
    Material_ShaderType_ShaderType_MIN;
  static const ShaderType ShaderType_MAX =
    Material_ShaderType_ShaderType_MAX;
  static const int ShaderType_ARRAYSIZE =
    Material_ShaderType_ShaderType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ShaderType_descriptor() {
    return Material_ShaderType_descriptor();
  }
  static inline const ::std::string& ShaderType_Name(ShaderType value) {
    return Material_ShaderType_Name(value);
  }
  static inline bool ShaderType_Parse(const ::std::string& name,
      ShaderType* value) {
    return Material_ShaderType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .gazebo.msgs.Material.Script script = 1;
  inline bool has_script() const;
  inline void clear_script();
  static const int kScriptFieldNumber = 1;
  inline const ::gazebo::msgs::Material_Script& script() const;
  inline ::gazebo::msgs::Material_Script* mutable_script();
  inline ::gazebo::msgs::Material_Script* release_script();
  inline void set_allocated_script(::gazebo::msgs::Material_Script* script);

  // optional .gazebo.msgs.Material.ShaderType shader_type = 2;
  inline bool has_shader_type() const;
  inline void clear_shader_type();
  static const int kShaderTypeFieldNumber = 2;
  inline ::gazebo::msgs::Material_ShaderType shader_type() const;
  inline void set_shader_type(::gazebo::msgs::Material_ShaderType value);

  // optional string normal_map = 3;
  inline bool has_normal_map() const;
  inline void clear_normal_map();
  static const int kNormalMapFieldNumber = 3;
  inline const ::std::string& normal_map() const;
  inline void set_normal_map(const ::std::string& value);
  inline void set_normal_map(const char* value);
  inline void set_normal_map(const char* value, size_t size);
  inline ::std::string* mutable_normal_map();
  inline ::std::string* release_normal_map();
  inline void set_allocated_normal_map(::std::string* normal_map);

  // optional .gazebo.msgs.Color ambient = 4;
  inline bool has_ambient() const;
  inline void clear_ambient();
  static const int kAmbientFieldNumber = 4;
  inline const ::gazebo::msgs::Color& ambient() const;
  inline ::gazebo::msgs::Color* mutable_ambient();
  inline ::gazebo::msgs::Color* release_ambient();
  inline void set_allocated_ambient(::gazebo::msgs::Color* ambient);

  // optional .gazebo.msgs.Color diffuse = 5;
  inline bool has_diffuse() const;
  inline void clear_diffuse();
  static const int kDiffuseFieldNumber = 5;
  inline const ::gazebo::msgs::Color& diffuse() const;
  inline ::gazebo::msgs::Color* mutable_diffuse();
  inline ::gazebo::msgs::Color* release_diffuse();
  inline void set_allocated_diffuse(::gazebo::msgs::Color* diffuse);

  // optional .gazebo.msgs.Color specular = 6;
  inline bool has_specular() const;
  inline void clear_specular();
  static const int kSpecularFieldNumber = 6;
  inline const ::gazebo::msgs::Color& specular() const;
  inline ::gazebo::msgs::Color* mutable_specular();
  inline ::gazebo::msgs::Color* release_specular();
  inline void set_allocated_specular(::gazebo::msgs::Color* specular);

  // optional .gazebo.msgs.Color emissive = 7;
  inline bool has_emissive() const;
  inline void clear_emissive();
  static const int kEmissiveFieldNumber = 7;
  inline const ::gazebo::msgs::Color& emissive() const;
  inline ::gazebo::msgs::Color* mutable_emissive();
  inline ::gazebo::msgs::Color* release_emissive();
  inline void set_allocated_emissive(::gazebo::msgs::Color* emissive);

  // optional bool lighting = 8;
  inline bool has_lighting() const;
  inline void clear_lighting();
  static const int kLightingFieldNumber = 8;
  inline bool lighting() const;
  inline void set_lighting(bool value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Material)
 private:
  inline void set_has_script();
  inline void clear_has_script();
  inline void set_has_shader_type();
  inline void clear_has_shader_type();
  inline void set_has_normal_map();
  inline void clear_has_normal_map();
  inline void set_has_ambient();
  inline void clear_has_ambient();
  inline void set_has_diffuse();
  inline void clear_has_diffuse();
  inline void set_has_specular();
  inline void clear_has_specular();
  inline void set_has_emissive();
  inline void clear_has_emissive();
  inline void set_has_lighting();
  inline void clear_has_lighting();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::gazebo::msgs::Material_Script* script_;
  ::std::string* normal_map_;
  ::gazebo::msgs::Color* ambient_;
  ::gazebo::msgs::Color* diffuse_;
  int shader_type_;
  bool lighting_;
  ::gazebo::msgs::Color* specular_;
  ::gazebo::msgs::Color* emissive_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_material_2eproto();
  friend void protobuf_AssignDesc_material_2eproto();
  friend void protobuf_ShutdownFile_material_2eproto();

  void InitAsDefaultInstance();
  static Material* default_instance_;
};
// ===================================================================


// ===================================================================

// Material_Script

// repeated string uri = 1;
inline int Material_Script::uri_size() const {
  return uri_.size();
}
inline void Material_Script::clear_uri() {
  uri_.Clear();
}
inline const ::std::string& Material_Script::uri(int index) const {
  return uri_.Get(index);
}
inline ::std::string* Material_Script::mutable_uri(int index) {
  return uri_.Mutable(index);
}
inline void Material_Script::set_uri(int index, const ::std::string& value) {
  uri_.Mutable(index)->assign(value);
}
inline void Material_Script::set_uri(int index, const char* value) {
  uri_.Mutable(index)->assign(value);
}
inline void Material_Script::set_uri(int index, const char* value, size_t size) {
  uri_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Material_Script::add_uri() {
  return uri_.Add();
}
inline void Material_Script::add_uri(const ::std::string& value) {
  uri_.Add()->assign(value);
}
inline void Material_Script::add_uri(const char* value) {
  uri_.Add()->assign(value);
}
inline void Material_Script::add_uri(const char* value, size_t size) {
  uri_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Material_Script::uri() const {
  return uri_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Material_Script::mutable_uri() {
  return &uri_;
}

// required string name = 2;
inline bool Material_Script::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Material_Script::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Material_Script::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Material_Script::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Material_Script::name() const {
  return *name_;
}
inline void Material_Script::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Material_Script::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Material_Script::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Material_Script::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Material_Script::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Material_Script::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Material

// optional .gazebo.msgs.Material.Script script = 1;
inline bool Material::has_script() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Material::set_has_script() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Material::clear_has_script() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Material::clear_script() {
  if (script_ != NULL) script_->::gazebo::msgs::Material_Script::Clear();
  clear_has_script();
}
inline const ::gazebo::msgs::Material_Script& Material::script() const {
  return script_ != NULL ? *script_ : *default_instance_->script_;
}
inline ::gazebo::msgs::Material_Script* Material::mutable_script() {
  set_has_script();
  if (script_ == NULL) script_ = new ::gazebo::msgs::Material_Script;
  return script_;
}
inline ::gazebo::msgs::Material_Script* Material::release_script() {
  clear_has_script();
  ::gazebo::msgs::Material_Script* temp = script_;
  script_ = NULL;
  return temp;
}
inline void Material::set_allocated_script(::gazebo::msgs::Material_Script* script) {
  delete script_;
  script_ = script;
  if (script) {
    set_has_script();
  } else {
    clear_has_script();
  }
}

// optional .gazebo.msgs.Material.ShaderType shader_type = 2;
inline bool Material::has_shader_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Material::set_has_shader_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Material::clear_has_shader_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Material::clear_shader_type() {
  shader_type_ = 1;
  clear_has_shader_type();
}
inline ::gazebo::msgs::Material_ShaderType Material::shader_type() const {
  return static_cast< ::gazebo::msgs::Material_ShaderType >(shader_type_);
}
inline void Material::set_shader_type(::gazebo::msgs::Material_ShaderType value) {
  assert(::gazebo::msgs::Material_ShaderType_IsValid(value));
  set_has_shader_type();
  shader_type_ = value;
}

// optional string normal_map = 3;
inline bool Material::has_normal_map() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Material::set_has_normal_map() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Material::clear_has_normal_map() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Material::clear_normal_map() {
  if (normal_map_ != &::google::protobuf::internal::kEmptyString) {
    normal_map_->clear();
  }
  clear_has_normal_map();
}
inline const ::std::string& Material::normal_map() const {
  return *normal_map_;
}
inline void Material::set_normal_map(const ::std::string& value) {
  set_has_normal_map();
  if (normal_map_ == &::google::protobuf::internal::kEmptyString) {
    normal_map_ = new ::std::string;
  }
  normal_map_->assign(value);
}
inline void Material::set_normal_map(const char* value) {
  set_has_normal_map();
  if (normal_map_ == &::google::protobuf::internal::kEmptyString) {
    normal_map_ = new ::std::string;
  }
  normal_map_->assign(value);
}
inline void Material::set_normal_map(const char* value, size_t size) {
  set_has_normal_map();
  if (normal_map_ == &::google::protobuf::internal::kEmptyString) {
    normal_map_ = new ::std::string;
  }
  normal_map_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Material::mutable_normal_map() {
  set_has_normal_map();
  if (normal_map_ == &::google::protobuf::internal::kEmptyString) {
    normal_map_ = new ::std::string;
  }
  return normal_map_;
}
inline ::std::string* Material::release_normal_map() {
  clear_has_normal_map();
  if (normal_map_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = normal_map_;
    normal_map_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Material::set_allocated_normal_map(::std::string* normal_map) {
  if (normal_map_ != &::google::protobuf::internal::kEmptyString) {
    delete normal_map_;
  }
  if (normal_map) {
    set_has_normal_map();
    normal_map_ = normal_map;
  } else {
    clear_has_normal_map();
    normal_map_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .gazebo.msgs.Color ambient = 4;
inline bool Material::has_ambient() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Material::set_has_ambient() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Material::clear_has_ambient() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Material::clear_ambient() {
  if (ambient_ != NULL) ambient_->::gazebo::msgs::Color::Clear();
  clear_has_ambient();
}
inline const ::gazebo::msgs::Color& Material::ambient() const {
  return ambient_ != NULL ? *ambient_ : *default_instance_->ambient_;
}
inline ::gazebo::msgs::Color* Material::mutable_ambient() {
  set_has_ambient();
  if (ambient_ == NULL) ambient_ = new ::gazebo::msgs::Color;
  return ambient_;
}
inline ::gazebo::msgs::Color* Material::release_ambient() {
  clear_has_ambient();
  ::gazebo::msgs::Color* temp = ambient_;
  ambient_ = NULL;
  return temp;
}
inline void Material::set_allocated_ambient(::gazebo::msgs::Color* ambient) {
  delete ambient_;
  ambient_ = ambient;
  if (ambient) {
    set_has_ambient();
  } else {
    clear_has_ambient();
  }
}

// optional .gazebo.msgs.Color diffuse = 5;
inline bool Material::has_diffuse() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Material::set_has_diffuse() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Material::clear_has_diffuse() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Material::clear_diffuse() {
  if (diffuse_ != NULL) diffuse_->::gazebo::msgs::Color::Clear();
  clear_has_diffuse();
}
inline const ::gazebo::msgs::Color& Material::diffuse() const {
  return diffuse_ != NULL ? *diffuse_ : *default_instance_->diffuse_;
}
inline ::gazebo::msgs::Color* Material::mutable_diffuse() {
  set_has_diffuse();
  if (diffuse_ == NULL) diffuse_ = new ::gazebo::msgs::Color;
  return diffuse_;
}
inline ::gazebo::msgs::Color* Material::release_diffuse() {
  clear_has_diffuse();
  ::gazebo::msgs::Color* temp = diffuse_;
  diffuse_ = NULL;
  return temp;
}
inline void Material::set_allocated_diffuse(::gazebo::msgs::Color* diffuse) {
  delete diffuse_;
  diffuse_ = diffuse;
  if (diffuse) {
    set_has_diffuse();
  } else {
    clear_has_diffuse();
  }
}

// optional .gazebo.msgs.Color specular = 6;
inline bool Material::has_specular() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Material::set_has_specular() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Material::clear_has_specular() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Material::clear_specular() {
  if (specular_ != NULL) specular_->::gazebo::msgs::Color::Clear();
  clear_has_specular();
}
inline const ::gazebo::msgs::Color& Material::specular() const {
  return specular_ != NULL ? *specular_ : *default_instance_->specular_;
}
inline ::gazebo::msgs::Color* Material::mutable_specular() {
  set_has_specular();
  if (specular_ == NULL) specular_ = new ::gazebo::msgs::Color;
  return specular_;
}
inline ::gazebo::msgs::Color* Material::release_specular() {
  clear_has_specular();
  ::gazebo::msgs::Color* temp = specular_;
  specular_ = NULL;
  return temp;
}
inline void Material::set_allocated_specular(::gazebo::msgs::Color* specular) {
  delete specular_;
  specular_ = specular;
  if (specular) {
    set_has_specular();
  } else {
    clear_has_specular();
  }
}

// optional .gazebo.msgs.Color emissive = 7;
inline bool Material::has_emissive() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Material::set_has_emissive() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Material::clear_has_emissive() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Material::clear_emissive() {
  if (emissive_ != NULL) emissive_->::gazebo::msgs::Color::Clear();
  clear_has_emissive();
}
inline const ::gazebo::msgs::Color& Material::emissive() const {
  return emissive_ != NULL ? *emissive_ : *default_instance_->emissive_;
}
inline ::gazebo::msgs::Color* Material::mutable_emissive() {
  set_has_emissive();
  if (emissive_ == NULL) emissive_ = new ::gazebo::msgs::Color;
  return emissive_;
}
inline ::gazebo::msgs::Color* Material::release_emissive() {
  clear_has_emissive();
  ::gazebo::msgs::Color* temp = emissive_;
  emissive_ = NULL;
  return temp;
}
inline void Material::set_allocated_emissive(::gazebo::msgs::Color* emissive) {
  delete emissive_;
  emissive_ = emissive;
  if (emissive) {
    set_has_emissive();
  } else {
    clear_has_emissive();
  }
}

// optional bool lighting = 8;
inline bool Material::has_lighting() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Material::set_has_lighting() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Material::clear_has_lighting() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Material::clear_lighting() {
  lighting_ = false;
  clear_has_lighting();
}
inline bool Material::lighting() const {
  return lighting_;
}
inline void Material::set_lighting(bool value) {
  set_has_lighting();
  lighting_ = value;
}


typedef boost::shared_ptr<gazebo::msgs::Material> MaterialPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gazebo::msgs::Material_ShaderType>() {
  return ::gazebo::msgs::Material_ShaderType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::Material const> ConstMaterialPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_material_2eproto__INCLUDED
