// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publishers.proto

#ifndef PROTOBUF_publishers_2eproto__INCLUDED
#define PROTOBUF_publishers_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "publish.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_publishers_2eproto();
void protobuf_AssignDesc_publishers_2eproto();
void protobuf_ShutdownFile_publishers_2eproto();

class Publishers;

// ===================================================================

class GZ_MSGS_VISIBLE Publishers : public ::google::protobuf::Message {
 public:
  Publishers();
  virtual ~Publishers();

  Publishers(const Publishers& from);

  inline Publishers& operator=(const Publishers& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Publishers& default_instance();

  void Swap(Publishers* other);

  // implements Message ----------------------------------------------

  Publishers* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Publishers& from);
  void MergeFrom(const Publishers& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gazebo.msgs.Publish publisher = 1;
  inline int publisher_size() const;
  inline void clear_publisher();
  static const int kPublisherFieldNumber = 1;
  inline const ::gazebo::msgs::Publish& publisher(int index) const;
  inline ::gazebo::msgs::Publish* mutable_publisher(int index);
  inline ::gazebo::msgs::Publish* add_publisher();
  inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Publish >&
      publisher() const;
  inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Publish >*
      mutable_publisher();

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Publishers)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Publish > publisher_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_publishers_2eproto();
  friend void protobuf_AssignDesc_publishers_2eproto();
  friend void protobuf_ShutdownFile_publishers_2eproto();

  void InitAsDefaultInstance();
  static Publishers* default_instance_;
};
// ===================================================================


// ===================================================================

// Publishers

// repeated .gazebo.msgs.Publish publisher = 1;
inline int Publishers::publisher_size() const {
  return publisher_.size();
}
inline void Publishers::clear_publisher() {
  publisher_.Clear();
}
inline const ::gazebo::msgs::Publish& Publishers::publisher(int index) const {
  return publisher_.Get(index);
}
inline ::gazebo::msgs::Publish* Publishers::mutable_publisher(int index) {
  return publisher_.Mutable(index);
}
inline ::gazebo::msgs::Publish* Publishers::add_publisher() {
  return publisher_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Publish >&
Publishers::publisher() const {
  return publisher_;
}
inline ::google::protobuf::RepeatedPtrField< ::gazebo::msgs::Publish >*
Publishers::mutable_publisher() {
  return &publisher_;
}


typedef boost::shared_ptr<gazebo::msgs::Publishers> PublishersPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::Publishers const> ConstPublishersPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_publishers_2eproto__INCLUDED
