// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raysensor.proto

#ifndef PROTOBUF_raysensor_2eproto__INCLUDED
#define PROTOBUF_raysensor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

// Internal implementation detail -- do not call these.
void GZ_MSGS_VISIBLE protobuf_AddDesc_raysensor_2eproto();
void protobuf_AssignDesc_raysensor_2eproto();
void protobuf_ShutdownFile_raysensor_2eproto();

class RaySensor;

// ===================================================================

class GZ_MSGS_VISIBLE RaySensor : public ::google::protobuf::Message {
 public:
  RaySensor();
  virtual ~RaySensor();

  RaySensor(const RaySensor& from);

  inline RaySensor& operator=(const RaySensor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaySensor& default_instance();

  void Swap(RaySensor* other);

  // implements Message ----------------------------------------------

  RaySensor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaySensor& from);
  void MergeFrom(const RaySensor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool display_scan = 1;
  inline bool has_display_scan() const;
  inline void clear_display_scan();
  static const int kDisplayScanFieldNumber = 1;
  inline bool display_scan() const;
  inline void set_display_scan(bool value);

  // optional int32 horizontal_samples = 2;
  inline bool has_horizontal_samples() const;
  inline void clear_horizontal_samples();
  static const int kHorizontalSamplesFieldNumber = 2;
  inline ::google::protobuf::int32 horizontal_samples() const;
  inline void set_horizontal_samples(::google::protobuf::int32 value);

  // optional double horizontal_resolution = 3;
  inline bool has_horizontal_resolution() const;
  inline void clear_horizontal_resolution();
  static const int kHorizontalResolutionFieldNumber = 3;
  inline double horizontal_resolution() const;
  inline void set_horizontal_resolution(double value);

  // optional double horizontal_min_angle = 4;
  inline bool has_horizontal_min_angle() const;
  inline void clear_horizontal_min_angle();
  static const int kHorizontalMinAngleFieldNumber = 4;
  inline double horizontal_min_angle() const;
  inline void set_horizontal_min_angle(double value);

  // optional double horizontal_max_angle = 5;
  inline bool has_horizontal_max_angle() const;
  inline void clear_horizontal_max_angle();
  static const int kHorizontalMaxAngleFieldNumber = 5;
  inline double horizontal_max_angle() const;
  inline void set_horizontal_max_angle(double value);

  // optional int32 vertical_samples = 6;
  inline bool has_vertical_samples() const;
  inline void clear_vertical_samples();
  static const int kVerticalSamplesFieldNumber = 6;
  inline ::google::protobuf::int32 vertical_samples() const;
  inline void set_vertical_samples(::google::protobuf::int32 value);

  // optional double vertical_resolution = 7;
  inline bool has_vertical_resolution() const;
  inline void clear_vertical_resolution();
  static const int kVerticalResolutionFieldNumber = 7;
  inline double vertical_resolution() const;
  inline void set_vertical_resolution(double value);

  // optional double vertical_min_angle = 8;
  inline bool has_vertical_min_angle() const;
  inline void clear_vertical_min_angle();
  static const int kVerticalMinAngleFieldNumber = 8;
  inline double vertical_min_angle() const;
  inline void set_vertical_min_angle(double value);

  // optional double vertical_max_angle = 9;
  inline bool has_vertical_max_angle() const;
  inline void clear_vertical_max_angle();
  static const int kVerticalMaxAngleFieldNumber = 9;
  inline double vertical_max_angle() const;
  inline void set_vertical_max_angle(double value);

  // optional double range_min = 10;
  inline bool has_range_min() const;
  inline void clear_range_min();
  static const int kRangeMinFieldNumber = 10;
  inline double range_min() const;
  inline void set_range_min(double value);

  // optional double range_max = 11;
  inline bool has_range_max() const;
  inline void clear_range_max();
  static const int kRangeMaxFieldNumber = 11;
  inline double range_max() const;
  inline void set_range_max(double value);

  // optional double range_resolution = 12;
  inline bool has_range_resolution() const;
  inline void clear_range_resolution();
  static const int kRangeResolutionFieldNumber = 12;
  inline double range_resolution() const;
  inline void set_range_resolution(double value);

  // @@protoc_insertion_point(class_scope:gazebo.msgs.RaySensor)
 private:
  inline void set_has_display_scan();
  inline void clear_has_display_scan();
  inline void set_has_horizontal_samples();
  inline void clear_has_horizontal_samples();
  inline void set_has_horizontal_resolution();
  inline void clear_has_horizontal_resolution();
  inline void set_has_horizontal_min_angle();
  inline void clear_has_horizontal_min_angle();
  inline void set_has_horizontal_max_angle();
  inline void clear_has_horizontal_max_angle();
  inline void set_has_vertical_samples();
  inline void clear_has_vertical_samples();
  inline void set_has_vertical_resolution();
  inline void clear_has_vertical_resolution();
  inline void set_has_vertical_min_angle();
  inline void clear_has_vertical_min_angle();
  inline void set_has_vertical_max_angle();
  inline void clear_has_vertical_max_angle();
  inline void set_has_range_min();
  inline void clear_has_range_min();
  inline void set_has_range_max();
  inline void clear_has_range_max();
  inline void set_has_range_resolution();
  inline void clear_has_range_resolution();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool display_scan_;
  ::google::protobuf::int32 horizontal_samples_;
  double horizontal_resolution_;
  double horizontal_min_angle_;
  double horizontal_max_angle_;
  double vertical_resolution_;
  double vertical_min_angle_;
  double vertical_max_angle_;
  double range_min_;
  double range_max_;
  double range_resolution_;
  ::google::protobuf::int32 vertical_samples_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];

  friend void GZ_MSGS_VISIBLE protobuf_AddDesc_raysensor_2eproto();
  friend void protobuf_AssignDesc_raysensor_2eproto();
  friend void protobuf_ShutdownFile_raysensor_2eproto();

  void InitAsDefaultInstance();
  static RaySensor* default_instance_;
};
// ===================================================================


// ===================================================================

// RaySensor

// optional bool display_scan = 1;
inline bool RaySensor::has_display_scan() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaySensor::set_has_display_scan() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaySensor::clear_has_display_scan() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaySensor::clear_display_scan() {
  display_scan_ = false;
  clear_has_display_scan();
}
inline bool RaySensor::display_scan() const {
  return display_scan_;
}
inline void RaySensor::set_display_scan(bool value) {
  set_has_display_scan();
  display_scan_ = value;
}

// optional int32 horizontal_samples = 2;
inline bool RaySensor::has_horizontal_samples() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaySensor::set_has_horizontal_samples() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaySensor::clear_has_horizontal_samples() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaySensor::clear_horizontal_samples() {
  horizontal_samples_ = 0;
  clear_has_horizontal_samples();
}
inline ::google::protobuf::int32 RaySensor::horizontal_samples() const {
  return horizontal_samples_;
}
inline void RaySensor::set_horizontal_samples(::google::protobuf::int32 value) {
  set_has_horizontal_samples();
  horizontal_samples_ = value;
}

// optional double horizontal_resolution = 3;
inline bool RaySensor::has_horizontal_resolution() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RaySensor::set_has_horizontal_resolution() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RaySensor::clear_has_horizontal_resolution() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RaySensor::clear_horizontal_resolution() {
  horizontal_resolution_ = 0;
  clear_has_horizontal_resolution();
}
inline double RaySensor::horizontal_resolution() const {
  return horizontal_resolution_;
}
inline void RaySensor::set_horizontal_resolution(double value) {
  set_has_horizontal_resolution();
  horizontal_resolution_ = value;
}

// optional double horizontal_min_angle = 4;
inline bool RaySensor::has_horizontal_min_angle() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RaySensor::set_has_horizontal_min_angle() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RaySensor::clear_has_horizontal_min_angle() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RaySensor::clear_horizontal_min_angle() {
  horizontal_min_angle_ = 0;
  clear_has_horizontal_min_angle();
}
inline double RaySensor::horizontal_min_angle() const {
  return horizontal_min_angle_;
}
inline void RaySensor::set_horizontal_min_angle(double value) {
  set_has_horizontal_min_angle();
  horizontal_min_angle_ = value;
}

// optional double horizontal_max_angle = 5;
inline bool RaySensor::has_horizontal_max_angle() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RaySensor::set_has_horizontal_max_angle() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RaySensor::clear_has_horizontal_max_angle() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RaySensor::clear_horizontal_max_angle() {
  horizontal_max_angle_ = 0;
  clear_has_horizontal_max_angle();
}
inline double RaySensor::horizontal_max_angle() const {
  return horizontal_max_angle_;
}
inline void RaySensor::set_horizontal_max_angle(double value) {
  set_has_horizontal_max_angle();
  horizontal_max_angle_ = value;
}

// optional int32 vertical_samples = 6;
inline bool RaySensor::has_vertical_samples() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RaySensor::set_has_vertical_samples() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RaySensor::clear_has_vertical_samples() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RaySensor::clear_vertical_samples() {
  vertical_samples_ = 0;
  clear_has_vertical_samples();
}
inline ::google::protobuf::int32 RaySensor::vertical_samples() const {
  return vertical_samples_;
}
inline void RaySensor::set_vertical_samples(::google::protobuf::int32 value) {
  set_has_vertical_samples();
  vertical_samples_ = value;
}

// optional double vertical_resolution = 7;
inline bool RaySensor::has_vertical_resolution() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RaySensor::set_has_vertical_resolution() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RaySensor::clear_has_vertical_resolution() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RaySensor::clear_vertical_resolution() {
  vertical_resolution_ = 0;
  clear_has_vertical_resolution();
}
inline double RaySensor::vertical_resolution() const {
  return vertical_resolution_;
}
inline void RaySensor::set_vertical_resolution(double value) {
  set_has_vertical_resolution();
  vertical_resolution_ = value;
}

// optional double vertical_min_angle = 8;
inline bool RaySensor::has_vertical_min_angle() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RaySensor::set_has_vertical_min_angle() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RaySensor::clear_has_vertical_min_angle() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RaySensor::clear_vertical_min_angle() {
  vertical_min_angle_ = 0;
  clear_has_vertical_min_angle();
}
inline double RaySensor::vertical_min_angle() const {
  return vertical_min_angle_;
}
inline void RaySensor::set_vertical_min_angle(double value) {
  set_has_vertical_min_angle();
  vertical_min_angle_ = value;
}

// optional double vertical_max_angle = 9;
inline bool RaySensor::has_vertical_max_angle() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RaySensor::set_has_vertical_max_angle() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RaySensor::clear_has_vertical_max_angle() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RaySensor::clear_vertical_max_angle() {
  vertical_max_angle_ = 0;
  clear_has_vertical_max_angle();
}
inline double RaySensor::vertical_max_angle() const {
  return vertical_max_angle_;
}
inline void RaySensor::set_vertical_max_angle(double value) {
  set_has_vertical_max_angle();
  vertical_max_angle_ = value;
}

// optional double range_min = 10;
inline bool RaySensor::has_range_min() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RaySensor::set_has_range_min() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RaySensor::clear_has_range_min() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RaySensor::clear_range_min() {
  range_min_ = 0;
  clear_has_range_min();
}
inline double RaySensor::range_min() const {
  return range_min_;
}
inline void RaySensor::set_range_min(double value) {
  set_has_range_min();
  range_min_ = value;
}

// optional double range_max = 11;
inline bool RaySensor::has_range_max() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RaySensor::set_has_range_max() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RaySensor::clear_has_range_max() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RaySensor::clear_range_max() {
  range_max_ = 0;
  clear_has_range_max();
}
inline double RaySensor::range_max() const {
  return range_max_;
}
inline void RaySensor::set_range_max(double value) {
  set_has_range_max();
  range_max_ = value;
}

// optional double range_resolution = 12;
inline bool RaySensor::has_range_resolution() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void RaySensor::set_has_range_resolution() {
  _has_bits_[0] |= 0x00000800u;
}
inline void RaySensor::clear_has_range_resolution() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void RaySensor::clear_range_resolution() {
  range_resolution_ = 0;
  clear_has_range_resolution();
}
inline double RaySensor::range_resolution() const {
  return range_resolution_;
}
inline void RaySensor::set_range_resolution(double value) {
  set_has_range_resolution();
  range_resolution_ = value;
}


typedef boost::shared_ptr<gazebo::msgs::RaySensor> RaySensorPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

typedef const boost::shared_ptr<gazebo::msgs::RaySensor const> ConstRaySensorPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_raysensor_2eproto__INCLUDED
