/* config.h. Generated by CMake for Gazebo. */
#ifndef _GAZEBO_CONFIG_H_
#define _GAZEBO_CONFIG_H_

/* Version number */
#define GAZEBO_MAJOR_VERSION 7
#define GAZEBO_MINOR_VERSION 5
#define GAZEBO_PATCH_VERSION 0

#define GAZEBO_VERSION "7.5"
#define GAZEBO_VERSION_FULL "7.5.0"

#define GAZEBO_VERSION_HEADER "Gazebo multi-robot simulator, version 7.5.0\nCopyright (C) 2012 Open Source Robotics Foundation.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\n"

/* #undef BUILD_TYPE_PROFILE */
/* #undef BUILD_TYPE_DEBUG */
/* #undef BUILD_TYPE_RELEASE */
/* #undef BUILD_TYPE_COVERAGE */
/* #undef HAVE_OPENAL */
#define HAVE_FFMPEG 1
/* #undef ENABLE_SHADOWS */
#define HAVE_BULLET 1
#define HAVE_SIMBODY 1
/* #undef HAVE_DART */
#define INCLUDE_RTSHADER 1
#define HAVE_GTS 1
/* #undef HAVE_QWT */
/* #undef ENABLE_DIAGNOSTICS */
#define HAVE_GDAL 1
#define HAVE_USB 1
/* #undef HAVE_OCULUS */
#define HAVE_SPNAV 1
/* #undef HDF5_INSTRUMENT */
/* #undef HAVE_GRAPHVIZ */
#define HAVE_UUID 1

#ifdef BUILD_TYPE_PROFILE
#include <google/heap-checker.h>
#endif

// ifndef _GAZEBO_CONFIG_H_
#endif
