%% define the DataRootMatrixStructure
function coreDataMatrix = coreDataStructure()
coreDataMatrix = struct('mpTrackMatrix',    [],...
                        'mpIsBadVec',       [],...
                        'mpDescMatrix',     [],...
                        'mpPosiMatrix',     [],...
                        'mpCount',           0,...
                        'mpTracksCountVec', [],...
                        'frPoseMatrix',     [],...
                        'frTypeMatrix',     [],...
                        'frImgDirMatrix',   [],...
                        'frImgIdVec',       [],...
                        'frCount',           0,...
                        'kpPosiMatrix',     [],...
                        'kpDescMatrix',     [],...
                        'kpMpIdMatrix',     [],...
                        'kpOctaveMatrix',   [],...
                        'kpsCountVec',      []);
%                     'imgSize',          [-1, -1],...
end               