// Automatically generated
#include <ignition/math/config.hh>
 #include <ignition/math/AffineException.hh>
 #include <ignition/math/Angle.hh>
 #include <ignition/math/Box.hh>
 #include <ignition/math/Filter.hh>
 #include <ignition/math/Frustum.hh>
 #include <ignition/math/Helpers.hh>
 #include <ignition/math/IndexException.hh>
 #include <ignition/math/Inertial.hh>
 #include <ignition/math/Kmeans.hh>
 #include <ignition/math/Line2.hh>
 #include <ignition/math/Line3.hh>
 #include <ignition/math/MassMatrix3.hh>
 #include <ignition/math/Matrix3.hh>
 #include <ignition/math/Matrix4.hh>
 #include <ignition/math/OrientedBox.hh>
 #include <ignition/math/PID.hh>
 #include <ignition/math/Plane.hh>
 #include <ignition/math/Pose3.hh>
 #include <ignition/math/Quaternion.hh>
 #include <ignition/math/Rand.hh>
 #include <ignition/math/RotationSpline.hh>
 #include <ignition/math/SemanticVersion.hh>
 #include <ignition/math/SignalStats.hh>
 #include <ignition/math/SphericalCoordinates.hh>
 #include <ignition/math/Spline.hh>
 #include <ignition/math/Temperature.hh>
 #include <ignition/math/Triangle.hh>
 #include <ignition/math/Triangle3.hh>
 #include <ignition/math/Vector2.hh>
 #include <ignition/math/Vector3.hh>
 #include <ignition/math/Vector3Stats.hh>
 #include <ignition/math/Vector4.hh>

